In [24]:
import pandas as pd
import numpy as np

data = {
    'patient_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 101, 107, 118, 119, 120],
    'age': ['25', '34', None, '45', '29', None, '38', '52', '27', '41',
            '33', 'unknown', '48', '26', '35', '25', '38', '31', None, '44'],
    'weight': ['70', '65', '80', None, '75', None, '68', '90', '72', '85',
               '78', None, '82', '69', 'N/A', '70', '68', '74', None, '88'],
    'blood_pressure': [120, 130, None, 140, 125, None, 135, None, 118, 145,
                      128, None, 138, 122, None, 120, 135, 126, None, 142],
    'medication': ['Aspirin', 'Metformin', 'Lisinopril', None, 'Aspirin',
                   'Metformin', 'Lisinopril', 'Aspirin', None, 'Metformin',
                   'Lisinopril', 'Aspirin', None, 'Metformin', 'Aspirin',
                   'Aspirin', 'Lisinopril', 'Metformin', 'Aspirin', None],
    'insurance_provider': ['Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None,
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', 'Blue Cross',
                          'Aetna', None, 'UnitedHealth', 'Blue Cross', 'Aetna',
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None]
}

df = pd.DataFrame(data)
# Task 1: Inspect the Data
# Use df.info() to view column data types and non-null counts
print("===========Printing info of dataframe=========")
df.info()

===========Printing info of dataframe=========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 17 non-null     object
 2   weight              16 non-null     object
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object
 5   insurance_provider  17 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ KB

In [16]:
print("===========Missing values per column=========")
# Use df.isnull().sum() to count missing values per column
df.isnull().sum()

===========Missing values per column=========

patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

In [18]:
# Calculate the percentage of missing values using: (df.isnull().sum() / len(df)) * 100
print("===========Percentage of missing values per column=========")
(df.isnull().sum() / len(df)) * 100

===========Percentage of missing values per column=========

patient_id             0.0
age                   15.0
weight                20.0
blood_pressure        30.0
medication            20.0
insurance_provider    15.0
dtype: float64

In [20]:
# Use df.duplicated().sum() to count duplicate rows
print("===========Duplicate rows=========")
df.duplicated().sum()

===========Duplicate rows=========

np.int64(2)

In [21]:
# Convert age column to numeric using
pd.to_numeric(df['age'], errors='coerce')

0     25.0
1     34.0
2      NaN
3     45.0
4     29.0
5      NaN
6     38.0
7     52.0
8     27.0
9     41.0
10    33.0
11     NaN
12    48.0
13    26.0
14    35.0
15    25.0
16    38.0
17    31.0
18     NaN
19    44.0
Name: age, dtype: float64

In [22]:
# Convert weight column to numeric using
pd.to_numeric(df['weight'], errors='coerce')

0     70.0
1     65.0
2     80.0
3      NaN
4     75.0
5      NaN
6     68.0
7     90.0
8     72.0
9     85.0
10    78.0
11     NaN
12    82.0
13    69.0
14     NaN
15    70.0
16    68.0
17    74.0
18     NaN
19    88.0
Name: weight, dtype: float64

In [27]:
# Check how many NEW missing values were created after conversion
df.isnull().sum()

patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

In [34]:
# Convert insurance_provider to category type using
df['insurance_provider'] = df['insurance_provider'].astype('category')

===========Printing info of dataframe=========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 17 non-null     object
 2   weight              16 non-null     object
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object
 5   insurance_provider  17 non-null     category
dtypes: category(1), float64(1), int64(1), object(3)
memory usage: 1.1+ KB

In [36]:
print("===========Printing dtypes of DF=========")
df.dtypes

===========Printing dtypes of DF=========

patient_id               int64
age                     object
weight                  object
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object

In [40]:
# Task 3: Handle Missing Values
# Apply appropriate strategies for each column:

# age: Fill with median
df['age'] = pd.to_numeric(df['age'], errors='coerce') # Convert to numeric
df['age'] = df['age'].fillna(df['age'].median())

# weight: Fill with median
df['weight'] = pd.to_numeric(df['weight'], errors='coerce') # Convert to numeric
df['weight'] = df['weight'].fillna(df['weight'].median())

# blood_pressure: Fill with median
df['blood_pressure'] = df['blood_pressure'].fillna(df['blood_pressure'].median())

# medication: Fill with mode
df['medication'] = df['medication'].fillna(df['medication'].mode()[0])

# insurance_provider: Fill with constant value 'Unknown'
# First, add 'Unknown' as a new category
df['insurance_provider'] = df['insurance_provider'].cat.add_categories('Unknown')
df['insurance_provider'] = df['insurance_provider'].fillna('Unknown')

# Display the DataFrame info after handling missing values
print("===========DataFrame info after handling missing values=========")
df.info()

# Display missing values count after handling
print("===========Missing values after handling=========")
df.isnull().sum()

===========DataFrame info after handling missing values=========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 20 non-null     float64
 2   weight              20 non-null     float64
 3   blood_pressure      20 non-null     float64
 4   medication          20 non-null     object
 5   insurance_provider  20 non-null     category
dtypes: category(1), float64(3), int64(1), object(1)
memory usage: 1.1+ KB
===========Missing values after handling=========

patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    0
dtype: int64

In [50]:
# Task 4: Handle Duplicates
# View duplicate rows using df[df.duplicated(keep=False)]
print("===========Duplicate rows=========")
df[df.duplicated(keep=False)]

===========Duplicate rows=========

Empty DataFrame
Columns: [patient_id, age, weight, blood_pressure, medication, insurance_provider]
Index: []

In [43]:
# Identify duplicates based on patient_id only using df.duplicated(subset=['patient_id'])
print("===========Duplicate rows based on patient_id only=========")
df[df.duplicated(subset=['patient_id'])]

===========Duplicate rows based on patient_id only=========

    patient_id   age  weight  blood_pressure  medication insurance_provider
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna

In [48]:
# Remove duplicates keeping first occurrence: df.drop_duplicates(subset=['patient_id'], keep='first')
print("===========Removing duplicates=========")
df = df.drop_duplicates(subset=['patient_id'], keep='first')

===========Removing duplicates=========

In [51]:
# Print shape before and after to show how many rows were removed
print("===========Shape before and after=========")
print("Shape before: ", df.shape)
df.info()

===========Shape before and after=========
Shape before:  (18, 6)
<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          18 non-null     int64
 1   age                 18 non-null     float64
 2   weight              18 non-null     float64
 3   blood_pressure      18 non-null     float64
 4   medication          18 non-null     object
 5   insurance_provider  18 non-null     category
dtypes: category(1), float64(3), int64(1), object(1)
memory usage: 1.1+ KB

In [58]:
print("\n--- Verification Report ---")

# Final Shape
final_shape = df_clean.shape
print(f"\nInitial Shape: {initial_shape}")
print(f"Final Shape: {final_shape}")

# Final Missing Values
final_missing_values = df_clean.isnull().sum()
print("\nInitial Missing Values:\n", initial_missing_values)
print("Final Missing Values:\n", final_missing_values)

# Final Duplicates (patient_id)
final_patient_id_duplicates = df_clean.duplicated(subset=['patient_id']).sum()
print(f"\nInitial Duplicates (patient_id): {initial_patient_id_duplicates}")
print(f"Final Duplicates (patient_id): {final_patient_id_duplicates}")

# Final Data Types
final_dtypes = df_clean.dtypes
print("\nInitial Data Types:\n", initial_dtypes)
print("Final Data Types:\n", final_dtypes)

print("\nCleaning workflow completed successfully.")

--- Verification Report ---

Initial Shape: (20, 6)
Final Shape: (18, 6)

Initial Missing Values:
 patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64
Final Missing Values:
 patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    0
dtype: int64

Initial Duplicates (patient_id): 2
Final Duplicates (patient_id): 0

Initial Data Types:
 patient_id              int64
age                    object
weight                 object
blood_pressure        float64
medication             object
insurance_provider     object
dtype: object
Final Data Types:
 patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object

Cleaning workflow completed successfully.